[package]
name = "ftd2xx-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ftd2xx-sys = { version="0.2.0", features=["static", "mpsse"] }
rand = "0.10.2"
regex = "1.13.1"
thiserror = "2.0.19"

[features]
# These tests require a FT4232H connected to an USB port.
test-ft4232h = []
# These tests require interactive input from the user.
test-interactive = []
# These tests require no probe connected to the host's computer.
test-dc = []
